Traceback (most recent call last):
  File "C:\Users\temir\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\temir\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\temir\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\temir\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\temir\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\temir\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\temir\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
q_w = [{
    "question": "What number of rows does the $\\nabla L $ have",
    "type": "numeric",
    "answers": [
        {
            "type": "value",
            "value": 5,
            "correct": True,
            "feedback": "Correct!"
        },
        {
            "type": "default",
            "feedback": "Incorrect answer! Scroll up for a hint"
        }
    ]
},
        {
    "question": "What number of columns does the $\\nabla L $ have",
    "type": "numeric",
    "answers": [
        {
            "type": "value",
            "value": 1,
            "correct": True,
            "feedback": "Correct!"
        },
        {
            "type": "default",
            "feedback": "Incorrect answer! Scroll up for a hint"
        }
    ]
    
    }
]
display_quiz(q_w)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[1], line 35[0m
[0;32m      1[0m q_w [38;5;241m=[39m [{
[0;32m      2[0m     [38;5;124m"[39m[38;5;124mquestion[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124mWhat number of rows does the $[39m[38;5;130;01m\\[39;00m[38;5;124mnabla L $ have[39m[38;5;124m"[39m,
[0;32m      3[0m     [38;5;124m"[39m[38;5;124mtype[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124mnumeric[39m[38;5;124m"[39m,
[1;32m   (...)[0m
[0;32m     33[0m     }
[0;32m     34[0m ]
[1;32m---> 35[0m [43mdisplay_quiz[49m(q_w)

[1;31mNameError[0m: name 'display_quiz' is not defined

